apiVersion: v1
entries:
  backend:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2024-02-01T14:08:29.938199405Z"
    description: A Helm chart for Kubernetes
    digest: 7e64f269ad14fe98168d02acf77a243b3ad43c268e301b5088b626882dc79ff1
    name: backend
    type: application
    urls:
    - https://github.com/Neha130/helm-charts/raw/main/backend-0.1.0.tgz
    version: 0.1.0
  helloworld:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2024-02-01T14:08:29.938824824Z"
    description: A Helm chart for Kubernetes
    digest: 6c0b9eefc4395aafaff58cce3d8b22a9405181753a7ca7b6eb8d164177f1c6c2
    name: helloworld
    type: application
    urls:
    - https://github.com/Neha130/helm-charts/raw/main/helloworld-0.1.0.tgz
    version: 0.1.0
  mongo:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2024-02-01T14:08:29.939402725Z"
    description: A Helm chart for Kubernetes
    digest: 7085057dd01592e09f7bd60e49380beeb9a0f0e0025866dc3e5b95720bad394f
    name: mongo
    type: application
    urls:
    - https://github.com/Neha130/helm-charts/raw/main/mongo-0.1.0.tgz
    version: 0.1.0
generated: "2024-02-01T14:08:29.936977356Z"
